# Generated by Django 4.1.4 on 2023-07-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='variant',
            new_name='variant_id',
        ),
    ]
